[2025-04-20T23:37:27.491+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:37:12.138079+00:00 [queued]>
[2025-04-20T23:37:27.502+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:37:12.138079+00:00 [queued]>
[2025-04-20T23:37:27.504+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-20T23:37:27.523+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt> on 2025-04-20 23:37:12.138079+00:00
[2025-04-20T23:37:27.531+0000] {standard_task_runner.py:60} INFO - Started process 188 to run task
[2025-04-20T23:37:27.535+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_csv_to_snowflake', 'run_dbt', 'manual__2025-04-20T23:37:12.138079+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ingest_bronze_dag.py', '--cfg-path', '/tmp/tmpgmbvj953']
[2025-04-20T23:37:27.538+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask run_dbt
[2025-04-20T23:37:27.589+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:37:12.138079+00:00 [running]> on host baa4deac6175
[2025-04-20T23:37:27.756+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_bronze_csv_to_snowflake' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T23:37:12.138079+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T23:37:12.138079+00:00'
[2025-04-20T23:37:27.764+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T23:37:27.767+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', ('cd /opt/***/edu_dbt && dbt run --full-refresh --profiles-dir /opt/***/edu_dbt/profiles',)]
[2025-04-20T23:37:27.771+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1770, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not tuple
[2025-04-20T23:37:27.787+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingest_bronze_csv_to_snowflake, task_id=run_dbt, execution_date=20250420T233712, start_date=20250420T233727, end_date=20250420T233727
[2025-04-20T23:37:27.804+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task run_dbt (expected str, bytes or os.PathLike object, not tuple; 188)
[2025-04-20T23:37:27.829+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-20T23:37:27.858+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
